name: TalkCo
options:
  bundleIdPrefix: com.talkco
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
targets:
  TalkCo:
    type: application
    platform: iOS
    sources:
      - TalkCo
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "TalkCo needs microphone access for English conversation practice."
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        SWIFT_VERSION: "5.9"
        DEVELOPMENT_TEAM: ""
    plist:
      path: TalkCo/Info.plist
      properties:
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true
